### ISSUE TITLE
Error on Laravel 5.5

### ISSUE THREAD

**Issue by gazatem** [vyuldashev/laravel-queue-rabbitmq#150]
I've had install and configures the package but when I start the work I've seen this error message in the logs. There is another issue similar this one but this is totally a fresh issue.

My log stack is here:

```
[2017-10-04 07:38:20] local.ERROR: Class  does not exist {"exception":"[object] (ReflectionException(code: -1): Class  does not exist at /var/www/monitor.app/vendor/laravel/framework/src/Illuminate/Container/Container.php:752)
[stacktrace]
#0 /var/www/monitor.app/vendor/laravel/framework/src/Illuminate/Container/Container.php(752): ReflectionClass->__construct('')
#1 /var/www/monitor.app/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\\Container\\Container->build(NULL)
#2 /var/www/monitor.app/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\\Container\\Container->resolve(NULL, Array)
#3 /var/www/monitor.app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(721): Illuminate\\Container\\Container->make(NULL, Array)
#4 /var/www/monitor.app/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(177): Illuminate\\Foundation\\Application->make(NULL)
#5 /var/www/monitor.app/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Queue/Jobs/RabbitMQJob.php(59): Illuminate\\Queue\\Jobs\\Job->resolve(NULL)
#6 /var/www/monitor.app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\Jobs\\RabbitMQJob->fire()
#7 /var/www/monitor.app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\\Queue\\Worker->process('rabbitmq', Object(VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\Jobs\\RabbitMQJob), Object(Illuminate\\Queue\\WorkerOptions))
#8 /var/www/monitor.app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(227): Illuminate\\Queue\\Worker->runJob(Object(VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\Jobs\\RabbitMQJob), 'rabbitmq', Object(Illuminate\\Queue\\WorkerOptions))
#9 /var/www/monitor.app/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->runNextJob('rabbitmq', 'logmessages', Object(Illuminate\\Queue\\WorkerOptions))
#10 /var/www/monitor.app/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(84): Illuminate\\Queue\\Console\\WorkCommand->runWorker('rabbitmq', 'logmessages')
#11 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#12 /var/www/monitor.app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#13 /var/www/monitor.app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#14 /var/www/monitor.app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#15 /var/www/monitor.app/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#16 /var/www/monitor.app/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Illuminate\\Container\\Container->call(Array)
#17 /var/www/monitor.app/vendor/symfony/console/Command/Command.php(264): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#18 /var/www/monitor.app/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#19 /var/www/monitor.app/vendor/symfony/console/Application.php(888): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /var/www/monitor.app/vendor/symfony/console/Application.php(224): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /var/www/monitor.app/vendor/symfony/console/Application.php(125): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 /var/www/monitor.app/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 /var/www/monitor.app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 /var/www/monitor.app/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 {main}
"}
``


I've got the same error while testing beanstalk. This problem might be related to Laravel 5.5. I do not think that my code is wrong since I did not complete the code just only added the structure.

**Comment by vyuldashev** [comment]
Something wrong with your framework setup.
