### ISSUE TITLE
v7.1.2 - Intermittent error - RabbitMQJob::getJobId() must be of the type string, null returned

### ISSUE THREAD

**Issue by pmill** [vyuldashev/laravel-queue-rabbitmq#217]
Hello

We are getting the following error intermittently when a message is being processed by the queue worker. Has anyone else encountered an issue like this?

Thanks
Peter

```
Symfony\Component\Debug\Exception\FatalThrowableError: Return value of VladimirYuldashev\LaravelQueueRabbitMQ\Queue\Jobs\RabbitMQJob::getJobId() must be of the type string, null returned
#25 vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Queue/Jobs/RabbitMQJob.php(137): getJobId
#24 vendor/illuminate/queue/Console/WorkCommand.php(175): writeStatus
#23 vendor/illuminate/queue/Console/WorkCommand.php(154): writeOutput
#22 vendor/illuminate/queue/Console/WorkCommand.php(129): Illuminate\Queue\Console\{closure}
#21 vendor/illuminate/events/Dispatcher.php(360): Illuminate\Events\{closure}
#20 vendor/illuminate/events/Dispatcher.php(209): dispatch
#19 vendor/illuminate/queue/Worker.php(453): raiseBeforeJobEvent
#18 vendor/illuminate/queue/Worker.php(318): process
#17 vendor/illuminate/queue/Worker.php(277): runJob
#16 vendor/illuminate/queue/Worker.php(230): runNextJob
#15 vendor/illuminate/queue/Console/WorkCommand.php(102): runWorker
#14 vendor/illuminate/queue/Console/WorkCommand.php(86): handle
#13 vendor/illuminate/queue/Console/WorkCommand.php(0): call_user_func_array
#12 vendor/illuminate/container/BoundMethod.php(29): Illuminate\Container\{closure}
#11 vendor/illuminate/container/BoundMethod.php(87): callBoundMethod
#10 vendor/illuminate/container/BoundMethod.php(31): call
#9 vendor/illuminate/container/Container.php(572): call
#8 vendor/illuminate/console/Command.php(183): execute
#7 vendor/symfony/console/Command/Command.php(255): run
#6 vendor/illuminate/console/Command.php(170): run
#5 vendor/symfony/console/Application.php(901): doRunCommand
#4 vendor/symfony/console/Application.php(262): doRun
#3 vendor/symfony/console/Application.php(145): run
#2 vendor/illuminate/console/Application.php(89): run
#1 vendor/laravel/lumen-framework/src/Console/Kernel.php(115): handle
#0 artisan(35): null
```

**Comment by stevenmyhre** [comment]
I am getting the same thing - any resolution?
