### ISSUE TITLE
 ErrorException: Use of undefined constant SOCKET_EAGAIN - assumed 'SOCKET_EAGAIN' (this will throw an Error in a future version of PHP)

### ISSUE THREAD

**Issue by nifrasismail** [vyuldashev/laravel-queue-rabbitmq#223]
When I tried with pushing the job to queue, I'm getting the following error logged. 

Php Version: 7.2.10

```
[2019-02-22 08:17:23] dev.ERROR: ErrorException: Use of undefined constant SOCKET_EAGAIN - assumed 'SOCKET_EAGAIN' (this will throw an Error in a future version of PHP) in /var/www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:88
Stack trace:
#0 /var/www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php(88): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(2, 'Use of undefine...', '/var/www/vendor...', 88, Array)
#1 /var/www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php(47): PhpAmqpLib\Wire\IO\StreamIO->__construct('172.18.0.4', 5672, 3, 3, NULL, false, 0)
#2 /var/www/vendor/enqueue/amqp-lib/AmqpConnectionFactory.php(133): PhpAmqpLib\Connection\AMQPStreamConnection->__construct('172.18.0.4', 5672, 'rabbitmq', 'rabbitmq', '/', false, 'AMQPLAIN', NULL, 'en_US', 3, 3, NULL, false, 0)
#3 /var/www/vendor/enqueue/amqp-lib/AmqpConnectionFactory.php(68): Enqueue\AmqpLib\AmqpConnectionFactory->establishConnection()
#4 /var/www/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Queue/Connectors/RabbitMQConnector.php(68): Enqueue\AmqpLib\AmqpConnectionFactory->createContext()
#5 /var/www/vendor/illuminate/queue/QueueManager.php(157): VladimirYuldashev\LaravelQueueRabbitMQ\Queue\Connectors\RabbitMQConnector->connect(Array)
#6 /var/www/vendor/illuminate/queue/QueueManager.php(138): Illuminate\Queue\QueueManager->resolve('rabbitmq')
#7 /var/www/vendor/illuminate/queue/QueueManager.php(268): Illuminate\Queue\QueueManager->connection()
#8 /var/www/vendor/illuminate/support/Facades/Facade.php(223): Illuminate\Queue\QueueManager->__call('push', Array)
#9 /var/www/app/ShipmentManagement/Base/Http/Controllers/ShipmentController.php(263): Illuminate\Support\Facades\Facade::__callStatic('push', Array)
#10 [internal function]: App\ShipmentManagement\Base\Http\Controllers\ShipmentController->testQueue()
#11 /var/www/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
#12 /var/www/vendor/illuminate/container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#13 /var/www/vendor/illuminate/container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#14 /var/www/vendor/illuminate/container/Container.php(572): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#15 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(376): Illuminate\Container\Container->call(Array, Array)
#16 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(342): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#17 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(316): Laravel\Lumen\Application->callLumenController(Object(App\ShipmentManagement\Base\Http\Controllers\ShipmentController), 'testQueue', Array)
#18 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(278): Laravel\Lumen\Application->callControllerAction(Array)
#19 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(258): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#20 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Laravel\Lumen\Http\Request))
#21 /var/www/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Laravel\Lumen\Http\Request))
#22 /var/www/app/Http/Middleware/ThrottleRequests.php(57): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Laravel\Lumen\Http\Request))
#23 /var/www/vendor/illuminate/pipeline/Pipeline.php(151): App\Http\Middleware\ThrottleRequests->handle(Object(Laravel\Lumen\Http\Request), Object(Closure), '500', '1')
#24 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Laravel\Lumen\Http\Request))
#25 /var/www/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Laravel\Lumen\Http\Request))
#26 /var/www/vendor/illuminate/pipeline/Pipeline.php(104): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Laravel\Lumen\Http\Request))
#27 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(413): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#28 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(259): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#29 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(163): Laravel\Lumen\Application->handleFoundRoute(Array)
#30 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Laravel\Lumen\Http\Request))
#31 /var/www/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Laravel\Lumen\Http\Request))
#32 /var/www/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Laravel\Lumen\Http\Request))
#33 /var/www/vendor/illuminate/pipeline/Pipeline.php(151): Barryvdh\Cors\HandlePreflight->handle(Object(Laravel\Lumen\Http\Request), Object(Closure))
#34 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Laravel\Lumen\Http\Request))
#35 /var/www/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Laravel\Lumen\Http\Request))
#36 /var/www/vendor/barryvdh/laravel-cors/src/HandleCors.php(36): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Laravel\Lumen\Http\Request))
#37 /var/www/vendor/illuminate/pipeline/Pipeline.php(151): Barryvdh\Cors\HandleCors->handle(Object(Laravel\Lumen\Http\Request), Object(Closure))
#38 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Laravel\Lumen\Http\Request))
#39 /var/www/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Laravel\Lumen\Http\Request))
#40 /var/www/vendor/illuminate/pipeline/Pipeline.php(104): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Laravel\Lumen\Http\Request))
#41 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(413): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#42 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(169): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#43 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(108): Laravel\Lumen\Application->dispatch(NULL)
#44 /var/www/public/index.php(28): Laravel\Lumen\Application->run()
#45 {main} {"exception":"[object] (ErrorException(code: 0): Use of undefined constant SOCKET_EAGAIN - assumed 'SOCKET_EAGAIN' (this will throw an Error in a future version of PHP) at /var/www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:88)
[stacktrace]
#0 /var/www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php(88): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(2, 'Use of undefine...', '/var/www/vendor...', 88, Array)
#1 /var/www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php(47): PhpAmqpLib\\Wire\\IO\\StreamIO->__construct('172.18.0.4', 5672, 3, 3, NULL, false, 0)
#2 /var/www/vendor/enqueue/amqp-lib/AmqpConnectionFactory.php(133): PhpAmqpLib\\Connection\\AMQPStreamConnection->__construct('172.18.0.4', 5672, 'rabbitmq', 'rabbitmq', '/', false, 'AMQPLAIN', NULL, 'en_US', 3, 3, NULL, false, 0)
#3 /var/www/vendor/enqueue/amqp-lib/AmqpConnectionFactory.php(68): Enqueue\\AmqpLib\\AmqpConnectionFactory->establishConnection()
#4 /var/www/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Queue/Connectors/RabbitMQConnector.php(68): Enqueue\\AmqpLib\\AmqpConnectionFactory->createContext()
#5 /var/www/vendor/illuminate/queue/QueueManager.php(157): VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\Connectors\\RabbitMQConnector->connect(Array)
#6 /var/www/vendor/illuminate/queue/QueueManager.php(138): Illuminate\\Queue\\QueueManager->resolve('rabbitmq')
#7 /var/www/vendor/illuminate/queue/QueueManager.php(268): Illuminate\\Queue\\QueueManager->connection()
#8 /var/www/vendor/illuminate/support/Facades/Facade.php(223): Illuminate\\Queue\\QueueManager->__call('push', Array)
#9 /var/www/app/ShipmentManagement/Base/Http/Controllers/ShipmentController.php(263): Illuminate\\Support\\Facades\\Facade::__callStatic('push', Array)
#10 [internal function]: App\\ShipmentManagement\\Base\\Http\\Controllers\\ShipmentController->testQueue()
#11 /var/www/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
#12 /var/www/vendor/illuminate/container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /var/www/vendor/illuminate/container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Laravel\\Lumen\\Application), Array, Object(Closure))
#14 /var/www/vendor/illuminate/container/Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Laravel\\Lumen\\Application), Array, Array, NULL)
#15 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(376): Illuminate\\Container\\Container->call(Array, Array)
#16 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(342): Laravel\\Lumen\\Application->callControllerCallable(Array, Array)
#17 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(316): Laravel\\Lumen\\Application->callLumenController(Object(App\\ShipmentManagement\\Base\\Http\\Controllers\\ShipmentController), 'testQueue', Array)
#18 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(278): Laravel\\Lumen\\Application->callControllerAction(Array)
#19 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(258): Laravel\\Lumen\\Application->callActionOnArrayBasedRoute(Array)
#20 [internal function]: Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#21 /var/www/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Laravel\\Lumen\\Http\\Request))
#22 /var/www/app/Http/Middleware/ThrottleRequests.php(57): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#23 /var/www/vendor/illuminate/pipeline/Pipeline.php(151): App\\Http\\Middleware\\ThrottleRequests->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure), '500', '1')
#24 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#25 /var/www/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Laravel\\Lumen\\Http\\Request))
#26 /var/www/vendor/illuminate/pipeline/Pipeline.php(104): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#27 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(413): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#28 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(259): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))
#29 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(163): Laravel\\Lumen\\Application->handleFoundRoute(Array)
#30 [internal function]: Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#31 /var/www/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Laravel\\Lumen\\Http\\Request))
#32 /var/www/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#33 /var/www/vendor/illuminate/pipeline/Pipeline.php(151): Barryvdh\\Cors\\HandlePreflight->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))
#34 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#35 /var/www/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Laravel\\Lumen\\Http\\Request))
#36 /var/www/vendor/barryvdh/laravel-cors/src/HandleCors.php(36): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#37 /var/www/vendor/illuminate/pipeline/Pipeline.php(151): Barryvdh\\Cors\\HandleCors->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))
#38 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#39 /var/www/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Laravel\\Lumen\\Http\\Request))
#40 /var/www/vendor/illuminate/pipeline/Pipeline.php(104): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#41 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(413): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#42 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(169): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))
#43 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(108): Laravel\\Lumen\\Application->dispatch(NULL)
#44 /var/www/public/index.php(28): Laravel\\Lumen\\Application->run()
#45 {main}
"} 

```

**Comment by nifrasismail** [comment]
I found something this is because of the version compatibility 

https://github.com/php-amqplib/php-amqplib/issues/619

**Comment by nifrasismail** [comment]
fixed by enabling the sockets in php

**Comment by vitahlin** [comment]
@nifrasismail Hello, I have this issse also.
Can you tell me how to enable socket in php?
I run php in docker [https://github.com/laradock/laradock/](https://github.com/laradock/laradock/)

**Comment by nifrasismail** [comment]
Please refer this on your laradock documentation
https://laradock.io/documentation/#edit-a-docker-image#install-php-extensions

M.
Nifras Ismail
Full Stack Developer



[image: mobile icon]  +94 75 80 363 00
[image: bird, twitter icon] nifras_tweety
<https://twitter.com/nifras_tweety?lang=en>
[image: circle, linkedin icon]
nifrasismail <https://www.linkedin.com/in/nifrasismail/>

[image: skype icon] nifras0094

**Comment by vitahlin** [comment]
@nifrasismail Thanks for your help.
