### ISSUE TITLE
Call to undefined method VladimirYuldashev\LaravelQueueRabbitMQ\Queue\RabbitMQQueue::readyNow()

### ISSUE THREAD

**Issue by vittorio-c** [vyuldashev/laravel-queue-rabbitmq#367]
Hello,

I know there is already an issue here : https://github.com/vyuldashev/laravel-queue-rabbitmq/issues/239
But there is no solution, expect upgrading the package.

I use : 
- "vladimir-yuldashev/laravel-queue-rabbitmq": "^10.2
- "laravel/horizon": "^3.0"
- "laravel/framework": "^6.0"

I get the error "Call to undefined method VladimirYuldashev\LaravelQueueRabbitMQ\Queue\RabbitMQQueue::readyNow()" when trying to lauch horizon from supervisorctl.

I get this error only on production, not on local. 

It looks like Horizon, or this package, is attaching readyNow() to the wrong class : it should call `VladimirYuldashev\\LaravelQueueRabbitMQ\\Horizon\\RabbitMQQueue::readyNow()` , which is what it does locally.

Do you have any idea how to solve this issue ?

Thanks

----

Full stacktrace : 

```
[2020-09-22 09:32:03] production.ERROR: Call to undefined method VladimirYuldashev\LaravelQueueRabbitMQ\Queue\RabbitMQQueue::readyNow()
{"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\RabbitMQQueue::readyNow() 
at /var/www/website/releases/1600699149176/vendor/laravel/horizon/src/AutoScaler.php:80)#012

[stacktrace]
#012#0 /var/www/website/releases/1600699149176/vendor/laravel/framework/src/Illuminate/Support/Collection.php(685): Laravel\\Horizon\\AutoScaler->Laravel\\Horizon\\{closure}(Object(Laravel\\Horizon\\ProcessPool), 'messages_aftale...')
#012#1 /var/www/website/releases/1600699149176/vendor/laravel/horizon/src/AutoScaler.php(86): Illuminate\\Support\\Collection->mapWithKeys(Object(Closure))
#012#2 /var/www/website/releases/1600699149176/vendor/laravel/horizon/src/AutoScaler.php(49): Laravel\\Horizon\\AutoScaler->timeToClearPerQueue(Object(Laravel\\Horizon\\Supervisor), Object(Illuminate\\Support\\Collection))
#012#3 /var/www/website/releases/1600699149176/vendor/laravel/horizon/src/Supervisor.php(343): Laravel\\Horizon\\AutoScaler->scale(Object(Laravel\\Horizon\\Supervisor))
#012#4 /var/www/website/releases/1600699149176/vendor/laravel/horizon/src/Supervisor.php(300): Laravel\\Horizon\\Supervisor->autoScale()
#012#5 /var/www/website/releases/1600699149176/vendor/laravel/horizon/src/Supervisor.php(267): Laravel\\Horizon\\Supervisor->loop()
#012#6 /var/www/website/releases/1600699149176/vendor/laravel/horizon/src/Console/SupervisorCommand.php(92): Laravel\\Horizon\\Supervisor->monitor()
#012#7 /var/www/website/releases/1600699149176/vendor/laravel/horizon/src/Console/SupervisorCommand.php(67): Laravel\\Horizon\\Console\\SupervisorCommand->start(Object(Laravel\\Horizon\\Supervisor))
#012#8 [internal function]: Laravel\\Horizon\\Console\\SupervisorCommand->handle(Object(Laravel\\Horizon\\SupervisorFactory))
#012#9 /var/www/website/releases/1600699149176/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#012#10 /var/www/website/releases/1600699149176/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#012#11 /var/www/website/releases/1600699149176/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#012#12 /var/www/website/releases/1600699149176/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#012#13 /var/www/website/releases/1600699149176/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#012#14 /var/www/website/releases/1600699149176/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
#012#15 /var/www/website/releases/1600699149176/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#012#16 /var/www/website/releases/1600699149176/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#012#17 /var/www/website/releases/1600699149176/vendor/symfony/console/Application.php(1001): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#012#18 /var/www/website/releases/1600699149176/vendor/symfony/console/Application.php(271): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\SupervisorCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#012#19 /var/www/website/releases/1600699149176/vendor/symfony/console/Application.php(147): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#012#20 /var/www/website/releases/1600699149176/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#012#21 /var/www/website/releases/1600699149176/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#012#22 /var/www/website/releases/1600699149176/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#012#23 {main}#012"}
```

**Comment by vyuldashev** [comment]
Sorry, according to our Support Policy we don't support Laravel 6.* anymore.
