### ISSUE TITLE
Call to undefined method VladimirYuldashev\LaravelQueueRabbitMQ\Queue\RabbitMQQueue::readyNow()

### ISSUE THREAD

**Issue by raftx24** [vyuldashev/laravel-queue-rabbitmq#375]
- Laravel/Lumen version: 8.14.0
- RabbitMQ version: 3.8.9
- Package version: 11.0.2

**Describe the bug**
I installed this package in clean laravel project besides horizon. after I ran `php artisan horizon` I got this error in my log.

```
[2020-11-15 11:42:56] local.ERROR: Call to undefined method VladimirYuldashev\LaravelQueueRabbitMQ\Queue\RabbitMQQueue::readyNow() {"exception":"[object] (Error(code: 0): Call to undefined method VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\RabbitMQQueue::readyNow() at /laravel/vendor/laravel/horizon/src/AutoScaler.php:80)
[stacktrace]
#0 /laravel/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(677): Laravel\\Horizon\\AutoScaler->Laravel\\Horizon\\{closure}(Object(Laravel\\Horizon\\ProcessPool), 'default')
#1 /laravel/vendor/laravel/horizon/src/AutoScaler.php(86): Illuminate\\Support\\Collection->mapWithKeys(Object(Closure))
#2 /laravel/vendor/laravel/horizon/src/AutoScaler.php(49): Laravel\\Horizon\\AutoScaler->timeToClearPerQueue(Object(Laravel\\Horizon\\Supervisor), Object(Illuminate\\Support\\Collection))
#3 /laravel/vendor/laravel/horizon/src/Supervisor.php(347): Laravel\\Horizon\\AutoScaler->scale(Object(Laravel\\Horizon\\Supervisor))
#4 /laravel/vendor/laravel/horizon/src/Supervisor.php(294): Laravel\\Horizon\\Supervisor->autoScale()
#5 /laravel/vendor/laravel/horizon/src/Supervisor.php(259): Laravel\\Horizon\\Supervisor->loop()
#6 /laravel/vendor/laravel/horizon/src/Console/SupervisorCommand.php(99): Laravel\\Horizon\\Supervisor->monitor()
#7 /laravel/vendor/laravel/horizon/src/Console/SupervisorCommand.php(74): Laravel\\Horizon\\Console\\SupervisorCommand->start(Object(Laravel\\Horizon\\Supervisor))
#8 /laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\SupervisorCommand->handle(Object(Laravel\\Horizon\\SupervisorFactory))
#9 /laravel/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#11 /laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#12 /laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#13 /laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call(Array)
#14 /laravel/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#15 /laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#16 /laravel/vendor/symfony/console/Application.php(920): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /laravel/vendor/symfony/console/Application.php(266): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Horizon\\Console\\SupervisorCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /laravel/vendor/symfony/console/Application.php(142): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /laravel/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /laravel/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 {main}
```

**Steps To Reproduce**

What steps needed, to reproduce this bug.

**Current behavior**

- What happens with the worker?
- Is the message retried or put back into the queue?
- Is the message acknowledged or rejected?
- Is the message unacked?
- Is the message gone?

**Expected behavior**

What is the expected behavior

**Additional context**

Add any other context about the problem or describe the use-case.

**Comment by raftx24** [comment]
I didn't install it correctly, fixed
