### ISSUE TITLE
laravel6 get errors

### ISSUE THREAD

**Issue by zhenjiang-huang** [vyuldashev/laravel-queue-rabbitmq#388]
hi,

I refer here:  https://github.com/vyuldashev/laravel-queue-rabbitmq#use-your-own-rabbitmqjob-class

then i run `php artisan queue:work --queue=xxx.queue.queue1` and  publish test message to rabbitmq,

get errors like below:

```
[2020-12-15 01:30:03] local.ERROR: Return value of VladimirYuldashev\LaravelQueueRabbitMQ\Queue\Jobs\RabbitMQJob::getJobId() must be of the type string, null returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\Jobs\\RabbitMQJob::getJobId() must be of the type string, null returned at /Applications/MAMP/htdocs/laravel6/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Queue/Jobs/RabbitMQJob.php:142)
[stacktrace]
#0 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(185): VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\Jobs\\RabbitMQJob->getJobId()
#1 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(168): Illuminate\\Queue\\Console\\WorkCommand->writeStatus(Object(VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\Jobs\\RabbitMQJob), 'Failed', 'error')
#2 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(147): Illuminate\\Queue\\Console\\WorkCommand->writeOutput(Object(VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\Jobs\\RabbitMQJob), 'failed')
#3 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(369): Illuminate\\Queue\\Console\\WorkCommand->Illuminate\\Queue\\Console\\{closure}(Object(Illuminate\\Queue\\Events\\JobFailed))
#4 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(218): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Illuminate\\\\Queu...', Array)
#5 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(185): Illuminate\\Events\\Dispatcher->dispatch('Illuminate\\\\Queu...')
#6 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(482): Illuminate\\Queue\\Jobs\\Job->fail(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#7 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(469): Illuminate\\Queue\\Worker->failJob(Object(VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\Jobs\\RabbitMQJob), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#8 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(399): Illuminate\\Queue\\Worker->markJobAsFailedIfWillExceedMaxAttempts('rabbitmq', Object(VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\Jobs\\RabbitMQJob), 1, Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#9 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(375): Illuminate\\Queue\\Worker->handleJobException('rabbitmq', Object(VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\Jobs\\RabbitMQJob), Object(Illuminate\\Queue\\WorkerOptions), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#10 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(314): Illuminate\\Queue\\Worker->process('rabbitmq', Object(VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\Jobs\\RabbitMQJob), Object(Illuminate\\Queue\\WorkerOptions))
#11 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(134): Illuminate\\Queue\\Worker->runJob(Object(VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\Jobs\\RabbitMQJob), 'rabbitmq', Object(Illuminate\\Queue\\WorkerOptions))
#12 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon('rabbitmq', 'xxx.queue.qu...', Object(Illuminate\\Queue\\WorkerOptions))
#13 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker('rabbitmq', 'xxx.queue.qu...')
#14 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#15 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#17 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#18 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#19 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
#20 /Applications/MAMP/htdocs/laravel6/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#21 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#22 /Applications/MAMP/htdocs/laravel6/vendor/symfony/console/Application.php(1009): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 /Applications/MAMP/htdocs/laravel6/vendor/symfony/console/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 /Applications/MAMP/htdocs/laravel6/vendor/symfony/console/Application.php(149): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 /Applications/MAMP/htdocs/laravel6/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 {main}

[previous exception] [object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [] does not exist. at /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Container/Container.php:805)
[stacktrace]
#0 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build(NULL)
#1 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\\Container\\Container->resolve(NULL, Array, true)
#2 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Foundation\\Application->resolve(NULL, Array)
#3 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\\Container\\Container->make(NULL, Array)
#4 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(215): Illuminate\\Foundation\\Application->make(NULL)
#5 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(202): Illuminate\\Queue\\Jobs\\Job->resolve(NULL)
#6 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(182): Illuminate\\Queue\\Jobs\\Job->failed(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#7 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(482): Illuminate\\Queue\\Jobs\\Job->fail(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#8 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(469): Illuminate\\Queue\\Worker->failJob(Object(VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\Jobs\\RabbitMQJob), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#9 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(399): Illuminate\\Queue\\Worker->markJobAsFailedIfWillExceedMaxAttempts('rabbitmq', Object(VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\Jobs\\RabbitMQJob), 1, Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#10 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(375): Illuminate\\Queue\\Worker->handleJobException('rabbitmq', Object(VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\Jobs\\RabbitMQJob), Object(Illuminate\\Queue\\WorkerOptions), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#11 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(314): Illuminate\\Queue\\Worker->process('rabbitmq', Object(VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\Jobs\\RabbitMQJob), Object(Illuminate\\Queue\\WorkerOptions))
#12 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(134): Illuminate\\Queue\\Worker->runJob(Object(VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\Jobs\\RabbitMQJob), 'rabbitmq', Object(Illuminate\\Queue\\WorkerOptions))
#13 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon('rabbitmq', 'xxx.queue.qu...', Object(Illuminate\\Queue\\WorkerOptions))
#14 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker('rabbitmq', 'xxx.queue.qu...')
#15 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#16 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#17 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#18 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#19 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#20 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
#21 /Applications/MAMP/htdocs/laravel6/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#22 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#23 /Applications/MAMP/htdocs/laravel6/vendor/symfony/console/Application.php(1009): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 /Applications/MAMP/htdocs/laravel6/vendor/symfony/console/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 /Applications/MAMP/htdocs/laravel6/vendor/symfony/console/Application.php(149): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 /Applications/MAMP/htdocs/laravel6/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#29 {main}

[previous exception] [object] (ReflectionException(code: -1): Class  does not exist at /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Container/Container.php:803)
[stacktrace]
#0 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Container/Container.php(803): ReflectionClass->__construct('')
#1 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build(NULL)
#2 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\\Container\\Container->resolve(NULL, Array, true)
#3 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Foundation\\Application->resolve(NULL, Array)
#4 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\\Container\\Container->make(NULL, Array)
#5 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(215): Illuminate\\Foundation\\Application->make(NULL)
#6 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(202): Illuminate\\Queue\\Jobs\\Job->resolve(NULL)
#7 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(182): Illuminate\\Queue\\Jobs\\Job->failed(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#8 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(482): Illuminate\\Queue\\Jobs\\Job->fail(Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#9 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(469): Illuminate\\Queue\\Worker->failJob(Object(VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\Jobs\\RabbitMQJob), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#10 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(399): Illuminate\\Queue\\Worker->markJobAsFailedIfWillExceedMaxAttempts('rabbitmq', Object(VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\Jobs\\RabbitMQJob), 1, Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#11 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(375): Illuminate\\Queue\\Worker->handleJobException('rabbitmq', Object(VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\Jobs\\RabbitMQJob), Object(Illuminate\\Queue\\WorkerOptions), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#12 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(314): Illuminate\\Queue\\Worker->process('rabbitmq', Object(VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\Jobs\\RabbitMQJob), Object(Illuminate\\Queue\\WorkerOptions))
#13 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(134): Illuminate\\Queue\\Worker->runJob(Object(VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\Jobs\\RabbitMQJob), 'rabbitmq', Object(Illuminate\\Queue\\WorkerOptions))
#14 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon('rabbitmq', 'xxx.queue.qu...', Object(Illuminate\\Queue\\WorkerOptions))
#15 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker('rabbitmq', 'xxx.queue.qu...')
#16 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#17 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#18 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#19 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#20 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#21 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
#22 /Applications/MAMP/htdocs/laravel6/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#23 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#24 /Applications/MAMP/htdocs/laravel6/vendor/symfony/console/Application.php(1009): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 /Applications/MAMP/htdocs/laravel6/vendor/symfony/console/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 /Applications/MAMP/htdocs/laravel6/vendor/symfony/console/Application.php(149): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 /Applications/MAMP/htdocs/laravel6/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#29 /Applications/MAMP/htdocs/laravel6/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#30 {main}
"} 

```

**Comment by M-Porter** [comment]
Closing due to laravel 6 being EOL.
