### ISSUE TITLE
How to reconnect when Broken pipe or closed connection

### ISSUE THREAD

**Issue by sujit-baniya** [vyuldashev/laravel-queue-rabbitmq#406]
Latest version of this package

```php
message=PhpAmqpLib\Exception\AMQPConnectionClosedException: Broken pipe or closed connection in /application/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:233
Stack trace:
#0 /application/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(388): PhpAmqpLib\Wire\IO\StreamIO->write('\x01\x00\x00\x00\x00\x00\v\x00\n\x002\x00\x00\x00\x00...')
#1 /application/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(516): PhpAmqpLib\Connection\AbstractConnection->write('\x01\x00\x00\x00\x00\x00\v\x00\n\x002\x00\x00\x00\x00...')
#2 /application/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(247): PhpAmqpLib\Connection\AbstractConnection->send_channel_method_frame(0, Array, Object(PhpAmqpLib\Wire\AMQPWriter))
#3 /application/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(724): PhpAmqpLib\Channel\AbstractChannel->send_method_frame(Array, Object(PhpAmqpLib\Wire\AMQPWriter))
#4 /application/vendor/intergo/rabbit-queue/src/Queue/RabbitMQQueue.php(595): PhpAmqpLib\Connection\AbstractConnection->close()
#5 /application/vendor/intergo/rabbit-queue/src/Queue/Connectors/RabbitMQConnector.php(59): Intergo\RabbitQueue\Queue\RabbitMQQueue->close()
#6 /application/vendor/illuminate/events/Dispatcher.php(369): Intergo\RabbitQueue\Queue\Connectors\RabbitMQConnector::Intergo\RabbitQueue\Queue\Connectors\{closure}(Object(Illuminate\Queue\Events\WorkerStopping))
#7 /application/vendor/illuminate/events/Dispatcher.php(218): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('Illuminate\\Queu...', Array)
#8 /application/vendor/illuminate/queue/Worker.php(602): Illuminate\Events\Dispatcher->dispatch('Illuminate\\Queu...')
#9 /application/vendor/intergo/rabbit-queue/src/Consumer.php(173): Illuminate\Queue\Worker->stop(0)
#10 /application/vendor/illuminate/queue/Worker.php(239): Intergo\RabbitQueue\Consumer->stop()
#11 /application/vendor/intergo/rabbit-queue/src/Consumer.php(142): Illuminate\Queue\Worker->stopIfNecessary(Object(Illuminate\Queue\WorkerOptions), NULL, NULL)
#12 /application/vendor/illuminate/queue/Console/WorkCommand.php(112): Intergo\RabbitQueue\Consumer->daemon('rabbitmq', 'msms-send-messa...', Object(Illuminate\Queue\WorkerOptions))
#13 /application/vendor/illuminate/queue/Console/WorkCommand.php(96): Illuminate\Queue\Console\WorkCommand->runWorker('rabbitmq', 'msms-send-messa...')
#14 /application/vendor/intergo/rabbit-queue/src/Console/ConsumeCommand.php(43): Illuminate\Queue\Console\WorkCommand->handle()
#15 /application/vendor/illuminate/container/BoundMethod.php(36): Intergo\RabbitQueue\Console\ConsumeCommand->handle()
#16 /application/vendor/illuminate/container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#17 /application/vendor/illuminate/container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#18 /application/vendor/illuminate/container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#19 /application/vendor/illuminate/container/Container.php(590): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#20 /application/vendor/illuminate/console/Command.php(134): Illuminate\Container\Container->call(Array)
#21 /application/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#22 /application/vendor/illuminate/console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#23 /application/vendor/symfony/console/Application.php(1009): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /application/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Intergo\RabbitQueue\Console\ConsumeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /application/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /application/vendor/illuminate/console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /application/vendor/laravel/lumen-framework/src/Console/Kernel.php(115): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /application/artisan(35): Laravel\Lumen\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 {main}, timestamp=2021-02-16T11:46:47.546Z, fields={exception={"class":"PhpAmqpLib\\Exception\\AMQPConnectionClosedException","message":"Broken pipe or closed connection","code":32,"file":"/application/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:233","trace":["/application/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:388","/application/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:516","/application/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:247","/application/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:724","/application/vendor/intergo/rabbit-queue/src/Queue/RabbitMQQueue.php:595","/application/vendor/intergo/rabbit-queue/src/Queue/Connectors/RabbitMQConnector.php:59","/application/vendor/illuminate/events/Dispatcher.php:369","/application/vendor/illuminate/events/Dispatcher.php:218","/application/vendor/illuminate/queue/Worker.php:602"
```

Ho can I reconnect the consumers when above error is received

**Comment by adm-bome** [comment]
In my opinion you don't reconnect.
Workers work...
And when a error occurs, your worker should probably die.

A manager like horizon or cron jobs an schedulers  or a supervisor script can then start a new worker when needed.


When u run into connection problems you probably want to figure out why this occurred. Somewhere an exeption was thrown and the worker or your job does not know how to handle the exception. So its safe to assume the worker must be dead or has to die.

**Comment by sujit-baniya** [comment]
@adm-bome Yes you're right...

There's one case where supervisor identifies the worker is UP but on RabbitMQ admin console, there's no consumer for queues. In fact the consumer are dead. At least, in my opinion, there should be a flag for reconnect where it reports the exception and try to reconnect. or may be a custom callback handler on exception

**Comment by acosta-edgar** [comment]
@adm-bome the thing is the worker is not dying when this, and other connection exceptions happen.

This has also been reported in #421 and #436 .

[This post shows how to handle it.](https://bestofphp.com/repo/php-amqplib-php-amqplib-php-queue#connection-recovery) IMHO it should be handled in `RabbitMQConnector`.

**Comment by khepin** [comment]
This issue is being closed due to its age. If you still are encountering the issue, please re-open so we can assist.
