### ISSUE TITLE
rabbitmq:consume executes jobs successfully but does not acknowledge them.

### ISSUE THREAD

**Issue by Nacoma** [vyuldashev/laravel-queue-rabbitmq#438]
- Laravel/Lumen version: 8.56.0
- Horizon version: 5.7.10
- RabbitMQ version: 3.8.2
- Package version: 11.3.0

`rabbitmq:consume` executes jobs successfully but does not acknowledge them. 

**Steps To Reproduce**
I've setup a repository that can be used to repro:  https://github.com/Nacoma/laravel-rabbitmq-repro

The first time you run `docker-compose up`  it fails because I didn't create the queue beforehand. This is expected.

After exiting the container, if you re-run it you will see the errors mentioned below.

**Current behavior**
- everything works as expected with `queue:work`
- everything works as expected with `rabbitmq:consume --once`
-  nothing works with `rabbitmq:consume`

Additional details:

```
λ  project release ✗ php artisan rabbitmq:consume
[2021-09-02 17:52:41][e9c5db0f-6f8a-4b0a-8177-d0f55839306f] Processing: Jobs\FakeJerb
[2021-09-02 17:52:41][0ff3b682-80a9-4dca-b4db-246ce56b4a81] Processing: Jobs\FakeJerb
[2021-09-02 17:52:41][4602382a-8743-45fe-8e53-9a88d031471f] Processing: Jobs\FakeJerb
[2021-09-02 17:52:41][6fee6756-c4f6-4486-9e50-cda1e32ad41b] Processing: Jobs\FakeJerb
[2021-09-02 17:52:41][4c5d1761-4543-4c9c-9a1b-393b99c51c41] Processing: Jobs\FakeJerb
[2021-09-02 17:52:41][742059f2-c2f1-488c-8744-003f418ca265] Processing: Jobs\FakeJerb
[2021-09-02 17:52:41][c930e9e6-07d3-4cb3-b0a3-740b715485d1] Processing: Jobs\FakeJerb
[2021-09-02 17:52:41][8416a51b-cdfa-44a1-9924-724695274c08] Processing: Jobs\FakeJerb
[2021-09-02 17:52:41][07c48775-9c9d-4405-a25b-a5da1c69340d] Processing: Jobs\FakeJerb
[2021-09-02 17:52:41][6d09a5f9-080e-4841-8913-0e3808e08a97] Processing: Jobs\FakeJerb
[2021-09-02 17:52:41][e0c5b870-e38c-4925-89de-ebb1ed4bfd5c] Processing: Jobs\FakeJerb
```

The following errors can are logged for each failure:

```
[2021-09-02 17:48:54] local.DEBUG: run
[2021-09-02 17:48:54] local.ERROR: ERR Error running script (call to f_0ac1d0b183ba9e097017cf4800a6a65400ae3539): @user_script:11: user_script:11: attempt to perform arithmetic on a nil value {"exception":"[object] (Predis\\Response\\ServerException(code: 0): ERR Error running script (call to f_0ac1d0b183ba9e097017cf4800a6a65400ae3539): @user_script:11: user_script:11: attempt to perform arithmetic on a nil value at /home/user/www/project/vendor/predis/predis/src/Client.php:370)
[stacktrace]
#0 /home/user/www/project/vendor/predis/predis/src/Client.php(335): Predis\\Client->onErrorResponse()
#1 /home/user/www/project/vendor/predis/predis/src/Client.php(314): Predis\\Client->executeCommand()
#2 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(116): Predis\\Client->__call()
#3 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(220): Illuminate\\Redis\\Connections\\Connection->command()
#4 /home/user/www/project/vendor/laravel/horizon/src/Repositories/RedisMetricsRepository.php(200): Illuminate\\Redis\\Connections\\Connection->__call()
#5 /home/user/www/project/vendor/laravel/horizon/src/Listeners/UpdateJobMetrics.php(53): Laravel\\Horizon\\Repositories\\RedisMetricsRepository->incrementQueue()
#6 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(424): Laravel\\Horizon\\Listeners\\UpdateJobMetrics->handle()
#7 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#8 /home/user/www/project/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Horizon/RabbitMQQueue.php(118): Illuminate\\Events\\Dispatcher->dispatch()
#9 /home/user/www/project/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Horizon/RabbitMQQueue.php(103): VladimirYuldashev\\LaravelQueueRabbitMQ\\Horizon\\RabbitMQQueue->event()
#10 /home/user/www/project/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Queue/Jobs/RabbitMQJob.php(114): VladimirYuldashev\\LaravelQueueRabbitMQ\\Horizon\\RabbitMQQueue->deleteReserved()
#11 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(82): VladimirYuldashev\\LaravelQueueRabbitMQ\\Queue\\Jobs\\RabbitMQJob->delete()
#12 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#13 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(428): Illuminate\\Queue\\Jobs\\Job->fire()
#14 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(378): Illuminate\\Queue\\Worker->process()
#15 /home/user/www/project/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Consumer.php(123): Illuminate\\Queue\\Worker->runJob()
#16 [internal function]: VladimirYuldashev\\LaravelQueueRabbitMQ\\Consumer->VladimirYuldashev\\LaravelQueueRabbitMQ\\{closure}()
#17 /home/user/www/project/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(1044): call_user_func()
#18 [internal function]: PhpAmqpLib\\Channel\\AMQPChannel->basic_deliver()
#19 /home/user/www/project/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(220): call_user_func()
#20 /home/user/www/project/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(374): PhpAmqpLib\\Channel\\AbstractChannel->dispatch()
#21 /home/user/www/project/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Consumer.php(145): PhpAmqpLib\\Channel\\AbstractChannel->wait()
#22 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(117): VladimirYuldashev\\LaravelQueueRabbitMQ\\Consumer->daemon()
#23 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#24 /home/user/www/project/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Console/ConsumeCommand.php(48): Illuminate\\Queue\\Console\\WorkCommand->handle()
#25 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): VladimirYuldashev\\LaravelQueueRabbitMQ\\Console\\ConsumeCommand->handle()
#26 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#27 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#28 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#29 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#30 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#31 /home/user/www/project/vendor/symfony/console/Command/Command.php(299): Illuminate\\Console\\Command->execute()
#32 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#33 /home/user/www/project/vendor/symfony/console/Application.php(978): Illuminate\\Console\\Command->run()
#34 /home/user/www/project/vendor/symfony/console/Application.php(295): Symfony\\Component\\Console\\Application->doRunCommand()
#35 /home/user/www/project/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
#36 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run()
#37 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#38 /home/user/www/project/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#39 {main}
"}
[2021-09-02 17:48:54] local.ERROR: PRECONDITION_FAILED - unknown delivery tag 1 {"exception":"[object] (PhpAmqpLib\\Exception\\AMQPProtocolChannelException(code: 406): PRECONDITION_FAILED - unknown delivery tag 1 at /home/user/www/project/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:216)
[stacktrace]
#0 [internal function]: PhpAmqpLib\\Channel\\AMQPChannel->channel_close()
#1 /home/user/www/project/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(217): call_user_func()
#2 /home/user/www/project/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(374): PhpAmqpLib\\Channel\\AbstractChannel->dispatch()
#3 /home/user/www/project/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Consumer.php(145): PhpAmqpLib\\Channel\\AbstractChannel->wait()
#4 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(117): VladimirYuldashev\\LaravelQueueRabbitMQ\\Consumer->daemon()
#5 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#6 /home/user/www/project/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Console/ConsumeCommand.php(48): Illuminate\\Queue\\Console\\WorkCommand->handle()
#7 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): VladimirYuldashev\\LaravelQueueRabbitMQ\\Console\\ConsumeCommand->handle()
#8 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#10 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#11 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#12 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#13 /home/user/www/project/vendor/symfony/console/Command/Command.php(299): Illuminate\\Console\\Command->execute()
#14 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#15 /home/user/www/project/vendor/symfony/console/Application.php(978): Illuminate\\Console\\Command->run()
#16 /home/user/www/project/vendor/symfony/console/Application.php(295): Symfony\\Component\\Console\\Application->doRunCommand()
#17 /home/user/www/project/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
#18 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run()
#19 /home/user/www/project/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#20 /home/user/www/project/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#21 {main}
"}
```

**Comment by khepin** [comment]
This issue is being closed due to its age. If you still are encountering the issue, please re-open so we can assist.
