### ISSUE TITLE
[Question] channel_error: "second 'channel.open' seen" when dispatching batch jobs

### ISSUE THREAD

**Issue by julwil** [vyuldashev/laravel-queue-rabbitmq#450]
- Laravel/Lumen version: 8.72.0
- RabbitMQ version: 3.7.10
- Package version: dev-master

**Describe the bug**
When dispatching a batch of jobs from our Laravel application (publisher), our RabbitMQ logs report a connection exception channel_error: "second 'channel.open' seen".  Also our worker logs (consumer) report the same error CHANNEL_ERROR - second 'channel.open' seen. Subsequently, the worker logs fill up with "Broken pipe or closed connection" errors. Nonetheless, the queued jobs are getting processed by the workers.

Dispatch batch (publisher)

        $batchJobs = Bus::batch([]);

        while (!empty($batch = $this->arrayShiftByCount($transitions, $maxBatch))) {
            // Queue the transitions to be executed
            $commandParameters['--transitions'] = $batch;
            $job = new RemoteCommandCallJob('ec:mass-state-transition', $commandParameters);
            $batchJobs->add([$job]);
        }
        
        $batchJobs->onQueue('state-transition')->dispatch();

RabbitMQ logs
`
2021-11-17 09:45:27.659 [error] <0.21590.3722> Error on AMQP connection <0.21590.3722> (XXX:60558 -> YYY:5672, vhost: '/', user: 'officeapp', state: running), channel 2: operation channel.open caused a connection exception channel_error: "second 'channel.open' seen"
`

Worker logs
`CHANNEL_ERROR - second 'channel.open' seen(20, 10)","file":"/srv/smartbridge-sc2-worker-1637140887/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php","line":760,"stack":["#0 [internal function]: PhpAmqpLib\\Connection\\AbstractConnection->connection_close()","#1 /srv/smartbridge-sc2-worker-1637140887/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(217): call_user_func()","#2 /srv/smartbridge-sc2-worker-1637140887/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(374): PhpAmqpLib\\Channel\\AbstractChannel->dispatch()"`

and then the worker logs fill up with
`"Broken pipe or closed connection","file":"/srv/smartbridge-sc2-worker-1637140887/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php","line":231,"stack":["#0 /srv/smartbridge-sc2-worker-1637140887/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(393): PhpAmqpLib\\Wire\\IO\\StreamIO->write()","#1 /srv/smartbridge-sc2-worker-1637140887/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(521): PhpAmqpLib\\Connection\\AbstractConnection->write()","#2 /srv/smartbridge-sc2-worker-1637140887/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(248): PhpAmqpLib\\Connection\\AbstractConnection->send_channel_method_frame()"`

**Steps To Reproduce**
This only happens on our staging environment and haven't yet been able to reproduce it locally.

**Current behavior**
- connection exception channel_error: "second 'channel.open' seen" occurs when dispatching batch
- Worker logs fill up with "Broken pipe or closed connection" error
- Messages are acked, messages are getting processed by workers

**Expected behavior**
- No "second 'channel.open' seen" error
- No "Broken pipe or closed connection" error

**Additional context**
config/queue.php

        'rabbitmq' => [

            'driver'     => 'rabbitmq',
            'queue'      => env('RABBITMQ_QUEUE', 'default'),
            'connection' => PhpAmqpLib\Connection\AMQPLazyConnection::class,

            'hosts' => [
                [
                    'host'     => env('RABBITMQ_HOST', '127.0.0.1'),
                    'port'     => env('RABBITMQ_PORT', 5672),
                    'user'     => env('RABBITMQ_USER', 'guest'),
                    'password' => env('RABBITMQ_PASSWORD', 'guest'),
                    'vhost'    => env('RABBITMQ_VHOST', '/'),
                ],
            ],

            'options' => [
                'keepalive'   => true,
                'ssl_options' => [
                    'cafile'      => env('RABBITMQ_SSL_CAFILE', null),
                    'local_cert'  => env('RABBITMQ_SSL_LOCALCERT', null),
                    'local_key'   => env('RABBITMQ_SSL_LOCALKEY', null),
                    'verify_peer' => env('RABBITMQ_SSL_VERIFY_PEER', true),
                    'passphrase'  => env('RABBITMQ_SSL_PASSPHRASE', null),
                ],
                'queue'       => [
                    'job' => VladimirYuldashev\LaravelQueueRabbitMQ\Queue\Jobs\RabbitMQJob::class,
                ],
            ],

            /*
             * Set to "horizon" if you wish to use Laravel Horizon.
             */
            'worker'  => env('RABBITMQ_WORKER', 'default'),

        ],

Supervisor

        [program:state-transition-worker]
        process_name=%(program_name)s_%(process_num)02d
        command=/bin/bash -c "echo $$ > /var/www/worker/supervisor/%(program_name)s_%(process_num)02d.pid; exec nice -n 10 ionice -c 2 -n 7 php /var/www/worker/artisan queue:work --queue=state-transition --sleep=3 --tries=1"
        autostart=true
        autorestart=true
        numprocs=2
        redirect_stderr=true
        stdout_logfile=/var/log/application/supervisord_www-data/state-transition-worker.log
        priority=500
        
        [program:state-transition-worker-observer]
        process_name=%(program_name)s_%(process_num)02d
        command=/bin/bash -c "exec cpulimit -l 50 -p `cat /var/www/worker/supervisor/state-transition-worker_%(process_num)02d.pid`"
        autostart=true
        autorestart=true
        numprocs=2
        redirect_stderr=true
        stdout_logfile=/var/log/application/supervisord_www-data/state-transition-worker.log
        priority=999

**Comment by julwil** [comment]
The problem was rooted in our supervisor config and was resolved by removing this:


    [program:state-transition-worker-observer]
    process_name=%(program_name)s_%(process_num)02d
    command=/bin/bash -c "exec cpulimit -l 50 -p `cat /var/www/worker/supervisor/state-transition-worker_%(process_num)02d.pid`"
    autostart=true
    autorestart=true
    numprocs=2
    redirect_stderr=true
    stdout_logfile=/var/log/application/supervisord_www-data/state-transition-worker.log
    priority=999

For some reason there was a cpu limit (e.g. 50 = 50%) on the worker process. When that limit was hit, the process got stopped. I assume this led to some weird behavior with RabbitMQ thinking the connection got closed.
